### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Hunkshang** [JasonWei512/wavenet_vocoder#1]
@JasonWei512 
用文章上提到的预训练模型，.pth 文件和一个Tacotron 生成的 .npy 文件。
执行命令  例如：python synthesis.py checkpoint_biaobei-36Khz.pth C:\Hunk\Projects\Tacotron\wavenet_vocoder-mandarin-biaobei --conditional=C:\Hunk\Projects\Tacotron\wavenet_vocoder-mandarin-biaobei\mel-batch_6_sentence_0.npy

会出现如下错误：
Traceback (most recent call last):
  File "synthesis.py", line 275, in <module>
    c = F.pad(c, pad=(cin_pad, cin_pad), mode="replicate")
  File "C:\Users\hunsha01\AppData\Local\Continuum\anaconda3\lib\site-packages\torch\nn\functional.py", line 2856, in pad
    return torch._C._nn.replication_pad1d(input, pad)
RuntimeError: non-empty 2D or 3D (batch mode) tensor expected for input。

不知道这是何故，还请帮忙看下，多谢！

**Comment by JasonWei512** [comment]
不清楚，没遇到过…
